# Generated by Django 5.1.4 on 2025-01-01 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Start Date & time')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='End Date & time')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Participant Name')),
                ('status', models.CharField(choices=[('Invited', 'INVITED'), ('Confirmed', 'CONFIRMED'), ('Declined', 'DECLINED'), ('Maybe', 'MAYBE'), ('Waiting list', 'WAITING_LIST')], default='invited', max_length=20, verbose_name='Status')),
                ('slug', models.SlugField(unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event')),
            ],
        ),
    ]
