# Generated by Django 5.1.4 on 2025-01-01 19:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Is Admin'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
