# Generated by Django 5.1.4 on 2025-01-06 12:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_slug_alter_participant_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date & time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Event name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start date & time'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.CharField(max_length=100, verbose_name='Name')),
                ('status', models.CharField(choices=[('Invited', 'INVITED'), ('Confirmed', 'CONFIRMED'), ('Declined', 'DECLINED'), ('Maybe', 'MAYBE'), ('Waiting list', 'WAITING_LIST')], max_length=20, verbose_name='Status')),
                ('slug', models.SlugField(default=uuid.uuid4, unique=True)),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is Admin')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event')),
            ],
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
